kind: EventStreams
apiVersion: eventstreams.ibm.com/v1beta2
metadata:
  name: pers-es
  namespace: cp4i
spec:
  version: latest
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  security:
    internalTls: NONE
  strimziOverrides:
    kafka:
      replicas: 3
      config:
        inter.broker.protocol.version: '3.3'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
        - name: kafkaes
          port: 9092
          type: route             //make it external
          tls: true               //setup secured with encryption
      storage:
        type: persistent-claim
        class: ibmc-file-gold-gid
        size: 500Mi
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: light-insecure-metrics-config
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: light-insecure-metrics-config
      storage:
        type: persistent-claim
        class: ibmc-file-gold-gid
        size: 500Mi
  requestIbmServices:
    iam: false
    monitoring: false
